# Numpy
![Scalar Vector Matrix Tensor](https://res.cloudinary.com/practicaldev/image/fetch/s--oTgfo1EL--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://raw.githubusercontent.com/adhiraiyan/DeepLearningWithTF2.0/master/notebooks/figures/fig0201a.png)

credit: https://res.cloudinary.com/

In [1]:
import numpy as np

In [2]:
numbers_list = [1, 2, 3, 4, 5, 6]
print(numbers_list)

[1, 2, 3, 4, 5, 6]


In [3]:
numbers_tuple = tuple([1, 2, 3, 4, 5, 6])
print(numbers_tuple)

(1, 2, 3, 4, 5, 6)


In [4]:
numbers_arr = np.array(1, 2, 3, 4, 5, 6)

TypeError: array() takes from 1 to 2 positional arguments but 6 were given

In [ ]:
help(np.array)

In [134]:
np.array([1, 2, 3, 4, 5]) * 3

array([ 3,  6,  9, 12, 15])

In [11]:
numbers_arr = np.array([1, 2, "ahmet", 4.0, 5, 6], np.int)
print(numbers_arr)

ValueError: invalid literal for int() with base 10: 'ahmet'

In [12]:
print(type(numbers_arr))
print(type(numbers_arr[0]))

<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [19]:
numbers_list / 2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [13]:
print(f"Before: {numbers_list[0]}")
numbers_list[0] = numbers_list[0] / 2
print(f"After: {numbers_list[0]}")

Before: 1
After: 2


In [15]:
numbers_arr / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [20]:
numbers_arr.shape

(6,)

In [136]:
numbers_arr = numbers_arr.reshape(1, 6)
numbers_arr.shape

(5, 2)


In [27]:
numbers_arr

array([[1, 2, 3, 4, 5, 6]])

### Most Used Methods (En Çok Kullanılan Metotlar)

In [28]:
np.sin(numbers_arr)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
        -0.2794155 ]])

In [29]:
np.cos(numbers_arr)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
         0.96017029]])

In [30]:
np.log(numbers_arr)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
        1.79175947]])

In [31]:
np.exp(numbers_arr) # e^x , 2.718281

array([[  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
        148.4131591 , 403.42879349]])

In [33]:
np.max(numbers_arr)

6

In [34]:
np.argmax(numbers_arr)

5

In [35]:
np.min(numbers_arr)

1

In [36]:
np.argmin(numbers_arr)

0

In [53]:
numbers_arr.exp()

AttributeError: 'numpy.ndarray' object has no attribute 'exp'

In [43]:
numbers_arr.sum()/numbers_arr.size

3.5

In [37]:
np.mean(numbers_arr)

3.5

In [54]:
np.std(numbers_arr)

1.707825127659933

In [55]:
numbers_arr = numbers_arr.reshape(2, 3)
print(numbers_arr)

[[1 2 3]
 [4 5 6]]


In [57]:
# axis=1 => Row
# axis=0 => Column
np.sum(numbers_arr, axis=1)

array([ 6, 15])

In [58]:
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [59]:
ones = np.ones((3, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
ones - 1

In [ ]:
zeros + 1

In [61]:
# Identity matrix
# Birim matris
eye = np.eye(3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
eye.diagonal()

array([1., 1., 1.])

In [66]:
np.diag(eye)

array([1., 1., 1.])

In [104]:
np.random.random((3, 3))

array([[0.07613947, 0.73788444, 0.7380232 ],
       [0.16279258, 0.36510622, 0.82936331],
       [0.84875315, 0.04818923, 0.9778784 ]])

### Slicing & Indexing (Dilimleme && İndisleme)

In [105]:
numbers_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
numbers_arr[0]

array([1, 2, 3])

In [110]:
# Ellipsis or :
numbers_arr[:, 0]

array([1, 4])

In [111]:
numbers_arr[:, 0: 3: 2]

array([[1, 3],
       [4, 6]])

In [112]:
print(numbers_arr[1, 0])
print(numbers_arr[0, 1])

4
2


In [113]:
numbers_arr > 2

array([[False, False,  True],
       [ True,  True,  True]])

In [114]:
numbers_arr[numbers_arr > 2]

array([3, 4, 5, 6])

In [118]:
# 3 index:
# 4 index:
# 5 index:
# 6 index: 
idx = np.where(numbers_arr > 2)

In [119]:
numbers_arr[idx]

array([3, 4, 5, 6])

In [120]:
eye = np.eye(3)
eye = eye + 2
print(eye)

[[3. 2. 2.]
 [2. 3. 2.]
 [2. 2. 3.]]


In [124]:
np.linalg.det(eye)

7.000000000000001

In [127]:
# Return evenly spaced numbers over a specified interval.
np.linspace(1.0, 10.0, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [132]:
for i in range(0, 10, 1):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [138]:
1.2 - 1.0

0.19999999999999996

In [137]:
round(1.2 - 1.0, 2)
round(0.2 + 0.1, 2)

0.3

More details about [floating point](https://docs.python.org/3/tutorial/floatingpoint.html#tut-fp-issues) in Python.

### Dot Product (İç Çarpım)
![Dot product](https://algebra1course.files.wordpress.com/2013/02/slide10.jpg)

credit: https://algebra1course.files.wordpress.com/

In [ ]:
arr_a = np.random.randint(1, 100, size=(5, 7))
arr_a

In [ ]:
arr_b = np.random.randint(1, 100, size=(5, 7))
arr_b

In [ ]:
arr_a * arr_b

In [ ]:
(arr_a * arr_b).shape

In [ ]:
arr_axb = np.dot(arr_a, arr_b)
arr_axb

In [ ]:
arr_a @ arr_b

### What now? (Şimdi ne olacak?)

![Advanced NumPy: Master stride tricks](https://miro.medium.com/max/1400/1*zss0Ayum0LBpN6fkzml1fw.png)

Credit: [Advanced NumPy: Master stride tricks](https://towardsdatascience.com/advanced-numpy-master-stride-tricks-with-25-illustrated-exercises-923a9393ab20#12e7)