### Tek satır for döngüsü (One-liner for)

In [99]:
kelime = "Python"
harf_listesi = []

for harf in kelime:
    harf_listesi.append(harf)
    
print(harf_listesi)

['P', 'y', 't', 'h', 'o', 'n']


In [102]:
harf_listesi = [harf for harf in "Python"]
print(harf_listesi)

['p', 'p', 'p', 'p', 'p', 'p']


### Tek satır if (One-liner if)

In [ ]:
koşul = 3

if koşul > 5:
    kelime = "Elma"
elif koşul > 7:
    
else:
    kelime = "Armut"

In [ ]:
kelime = "Elma" if koşul else "Armut" if koşul > 5 else "Çilek"

### Tek satır fonksiyon Lambda (One-liner function Lambda)

In [103]:
kare_al = lambda x: x**2
kare_al(5)

25

### map, reduce, filter, zip fonksiyonları

In [104]:
sayılar = [1, 2, 3, 4, 5, 6, 7]
sayıların_kareleri = []

for sayı in sayılar:
    sayıların_kareleri.append(kare_al(sayı))
print(sayıların_kareleri)

[1, 4, 9, 16, 25, 36, 49]


In [108]:
sayıların_kareleri =  map(kare_al, sayılar)
print(sayıların_kareleri)
for sayı in sayıların_kareleri:
    print(sayı)


1
4
9
16
25
36
49


In [109]:
from functools import reduce

sayılar = [1, 6, 3, 7, 10, 0]
print(reduce(lambda x,y: x if x > y else y, sayılar))

10


In [111]:
def beşten_uzun(kelime):
    if len(kelime) > 5:
        return True
    else:
        return False
isimler = ['Oğuz', 'Ahmet', 'Necati', 'Ali', 'Mehmet', 'Ziya']
uzun_isimler = filter(beşten_uzun, isimler)
print(uzun_isimler)
for isim in uzun_isimler:
    print(isim)

Necati
Mehmet


In [113]:
sayılar = [0, 1, 2, 3, 4, 5]
isimler = ['Oğuz', 'Ahmet', 'Necati', 'Ali', 'Mehmet', 'Ziya']


for i, j in zip(sayılar, isimler):
    print(i)


(0, 'Oğuz')
(1, 'Ahmet')
(2, 'Necati')
(3, 'Ali')
(4, 'Mehmet')
(5, 'Ziya')


### Assert anahtar kelimesi ( Assert keyword )

In [116]:
yaş = input("Yaşınız:")
assert int(yaş) >= 0, "Yaşınız negatif olamaz"

Yaşınız: -2


AssertionError: Yaşınız negatif olamaz

### Üreteçler (Generators)

In [117]:
def generator():
    i = 1
    print('Öncelikle bu basıldı')
    yield i

    i += 1
    print('Sonra bu')
    yield i

for eleman in generator():
    print("For döngüsü içinde:", eleman)
#print(next())

Öncelikle bu basıldı
For döngüsü içinde: 1
Sonra bu
For döngüsü içinde: 2


In [118]:
a = 5

def outer():
    a = 3
    def inner():
        nonlocal a
        a += 5
        print("inner fonksiyon:", a)
    print("outer fonksiyon:", a)
    return inner()

outer()
print("global:", a)

outer fonksiyon: 3
inner fonksiyon: 8
global: 5


### Decorators

In [123]:
from datetime import datetime

def show_time(func):
    def wrapper(name):
        print("Time:", datetime.now().time())
        func(name)
    return wrapper

@show_time
def say_hi(name="John"):
    print("Hi {}!".format(name))

say_hi("Ahmet")

TypeError: wrapper() takes 0 positional arguments but 1 was given

# Numpy

![Scalar Vector Matrix Tensor](https://res.cloudinary.com/practicaldev/image/fetch/s--oTgfo1EL--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://raw.githubusercontent.com/adhiraiyan/DeepLearningWithTF2.0/master/notebooks/figures/fig0201a.png)

In [124]:
import numpy as np

In [125]:
a = np.array([10, 20, 30, 40, 50, 60])
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(6,)


In [132]:
type(a[3])

numpy.int64

In [133]:
a[2] *= 2
print(a[2])

60


In [134]:
a

array([10, 20, 60, 40, 50, 60])

In [135]:
b = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(b)
print(b.shape)
print(b.dtype)

[[10 20 30]
 [40 50 60]]
(2, 3)
int64


In [136]:
a = np.array([10, 20, 30, 40, 50, 60])
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485,
       -0.30481062])

In [137]:
np.cos(a)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603,
       -0.95241298])

In [138]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301,
       4.09434456])

In [139]:
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21, 1.14200739e+26])

In [140]:
np.max(a)

60

In [141]:
np.min(a)

10

In [142]:
np.argmax(a)

5

In [143]:
np.mean(a)

35.0

In [144]:
np.median(a)

35.0

In [145]:
np.std(a)

17.07825127659933

In [146]:
b

array([[10, 20, 30],
       [40, 50, 60]])

In [149]:
# axis=1 => Row
# axis=0 => Column
np.sum(b, axis=0)

array([50, 70, 90])

In [150]:
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [151]:
ones = np.ones((3, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [152]:
full = np.full((3, 3), 5)
print(full)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [155]:
eye = np.eye(5)
print(eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [161]:
arange = np.arange(7)
print(arange)

arange = np.arange(0, 10, 2)
print(arange)

[0 1 2 3 4 5 6]
[0 2 4 6 8]


In [170]:
# Create randint
random = np.random.random((3, 3))
print(random)

int64


In [171]:
arr = np.random.randint(20, size=(5, 5))
print(arr)

[[12 11 16  5 18]
 [19 15 18 16  8]
 [10 13  1  7  5]
 [ 4 13  2  5 16]
 [19  9  1  8 10]]


In [173]:
zeros*6

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [181]:
arr

array([[12, 11, 16,  5, 18],
       [19, 15, 18, 16,  8],
       [10, 13,  1,  7,  5],
       [ 4, 13,  2,  5, 16],
       [19,  9,  1,  8, 10]])

In [185]:
arr[0:3, ::]
#arr[satır, sütun]

array([[12, 11, 16,  5, 18],
       [19, 15, 18, 16,  8],
       [10, 13,  1,  7,  5]])

In [192]:
arr[arr > 10]

array([12, 11, 16, 18, 19, 15, 18, 16, 13, 13, 16, 19])

In [194]:
np.where(arr > 10)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 3, 3, 4]),
 array([0, 1, 2, 4, 0, 1, 2, 3, 1, 1, 4, 0]))

In [204]:
np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]).reshape(3, -1).shape

(3, 4)

In [206]:
c = np.random.randint(10, size=(3, 3))
print(c)
c_inv = np.linalg.inv(c)
print(c_inv)

[[1 8 2]
 [4 7 8]
 [5 9 0]]
[[-0.288  0.072  0.2  ]
 [ 0.16  -0.04   0.   ]
 [ 0.004  0.124 -0.1  ]]


## İç Çarpım (Dot product)
![Dot product](https://algebra1course.files.wordpress.com/2013/02/slide10.jpg)

credit: https://algebra1course.files.wordpress.com/

In [207]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(a.shape)

(2, 3)


In [208]:
b = np.array([
    [7, 8, 9],
    [10, 11, 12]
])
print(a.shape)

(2, 3)


In [209]:
axb = np.dot(a, b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [213]:
# Transpose
(b.T).shape

(3, 2)

In [214]:
axb = np.dot(a, b.T)
print(axb)
print(axb.shape)

[[ 50  68]
 [122 167]]
(2, 2)
